### ISSUE TITLE
Mobile app milestones

### ISSUE THREAD

**Issue by cazci** [scorelab/LabelLab#423]
<details>
  <summary>UI Mockups</summary>

| Image details screen | Image path screen  |
|---|---|
| ![Screen 1](https://user-images.githubusercontent.com/32796120/82793110-01be1300-9e8e-11ea-85c4-26d446006951.png) | ![Screen 2](https://user-images.githubusercontent.com/32796120/82793175-1bf7f100-9e8e-11ea-9edb-5d766bad0c8a.png) |

| Images screen | Feedback screen  |
|---|---|
| ![Screen 3](https://user-images.githubusercontent.com/32796120/82793831-3088b900-9e8f-11ea-9654-ba5878d78fe9.png) | ![Screen 7](https://user-images.githubusercontent.com/32796120/82793848-37173080-9e8f-11ea-8f40-c3d9b8d4df15.png) |

| Edit image screen | Version history screen  |
|---|---|
| ![Screen 6](https://user-images.githubusercontent.com/32796120/82794261-ce7c8380-9e8f-11ea-955a-4ae0526c277c.png) | ![Screen 5](https://user-images.githubusercontent.com/32796120/82794172-adb42e00-9e8f-11ea-85f1-a664d0d04153.png) |
</details>

## Milestone 1 | #286 #289 
- [x] Create OpenAPI spec
- [x] Design UI sketches
- [x] Migrate to the new backend
    - [x] Update tables
    - [x] Write controllers
    - [x] Update client side code
- [x] Implement image path tracking
    - [x] Implement map screen
    - [x] Integrate Google Maps & Path APIs
    - [x] Write backend connections
    - [x] Write backend logic
    - [x] Test connections
- [x] Update multiple image upload
- [x] Update label edit and delete
- [x] Update image selection
    - [x] Add selection tag editing
    - [x] Add selection resizing
- [ ] Update image editing tool
    - [ ] Add uploaded images editing support
    - [x] Add image resizing
- [ ] Write tests
    - [ ] Write widget tests
- [x] Update documentation

## Milestone 2 | #287 
- [x] Implement image group screen
- [ ] Update backend grouping logic 
- [x] Implement screens for training
- [x] Implement multiple image selection
- [x] Write logic for initializing training
    - [ ] Write integration tests
- [x] Implement screens for training results
- [x] Test for sample image bulks
- [ ] Implement image classification
    - [ ] Update screens
    - [ ] Write backend logic
    - [ ] Write backend tests
- [ ] Update documentation

## Milestone 3 | #288 
- [x] Implement model version history viewer
    - [x] Update screens
    - [x] Connect backend
- [ ] Update client side loigc
- [ ] Write integration tests
- [ ] Integrate CodeCov
- [ ] Update documentation
