### ISSUE TITLE
Revamp the Web Application

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#424]
This is a comprehensive list of the milestones to be achieved for Revamping the Backend-
### Milestone 1- (Issue #283)
- [x] Finalize the idea and structure of the project.
- [x] Set up basic layout of the backend server Flask and integrate the database.
- [x] Start writing new models.
- [x] Write Auth, Projects, Labels, Images, Users routes.
- [x] Implement user token as well as OAuth2 based authentication with Google,  Facebook, GitHub.
- [x] Start writing tests for existing frontend in react and redux and for the backend.
- [x] complete documentation for the labeller (Issue #291).
### Milestone 2- (Issue #283)
- [x] Implement the functions to convert data to be displayed as statistical diagrams.
- [x] Write Analytics and Classification routes.
- [x] Start making the Image formatting/editing tool.
- [x] Implement the Team feature inside the projects. Including the changes needed to the frontend.
- [x] Complete the tests for the code base (Issue #290).
- [ ] Implementing analytics and summary data sharing and downloading.
### Milestone 3-
- [x] Path Tracking feature will be implemented in the number of images using ExifTool (extracts metadata) (Issue #284).
- [x] Marking of latitudes and longitudes extracted from the image’s metadata track.log generated file on the map with Polylines feature of Google maps.
- [ ] Dockerize the LabelLab Flask server edit the existing docker-compose file for the frontend changes.
- [ ] Deploy the containerized app to GCP
- [ ] Integrating the two builds and test cases with Travis.
- [ ] Fix bugs and polish the new features and review the documentation (Issue #291).

**Comment by carpecodeum** [comment]
@UdeshUK can we please reopen this? :)
